lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: 'pass_phrase'

# lexik_jwt_authentication:
#     secret_key: '%env(resolve:JWT_SECRET_KEY)%'
#     public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
#     pass_phrase: '%env(JWT_PASSPHRASE)%'
