services:
  php-symfony:
    image: php:8.2-cli
    container_name: php-symfony
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8082:8082"
    depends_on:
      - composer
    command: >
      sh -c "php -S 0.0.0.0:8082 -t public"
  
  composer:
    image: composer:2.8.3
    container_name: composer-install
    volumes:
      - ./:/app
    working_dir: /app
    command: ["composer", "install", "--no-interaction", "--optimize-autoloader"]
