services:
  php-symfony:
    build: .
    container_name: php-symfony
    ports:
      - "8082:8082"

  vue-app:
    image: node:lts
    container_name: vue-app
    environment:
      - VITE_API_URL=http://localhost:8080
      - VITE_API_CRYPTO_URL=http://localhost:8082
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install && npm run dev -- --host"